// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIspHJ54IoG1SKMEWcjEevyUPDfO4-8uU',
    appId: '1:41295353179:web:d442cf6aff90d539eef67e',
    messagingSenderId: '41295353179',
    projectId: 'storyteller-d0cdd',
    authDomain: 'storyteller-d0cdd.firebaseapp.com',
    storageBucket: 'storyteller-d0cdd.appspot.com',
    measurementId: 'G-8LC06N2SBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxG5itA7TsXn4yQ8tjxKg6EkvG9mSr6Wc',
    appId: '1:41295353179:android:a07427d873247b63eef67e',
    messagingSenderId: '41295353179',
    projectId: 'storyteller-d0cdd',
    storageBucket: 'storyteller-d0cdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBam1xjgfEhS8-aVpxmEp2iU-juPvb7_qw',
    appId: '1:41295353179:ios:2be74a0534f7308deef67e',
    messagingSenderId: '41295353179',
    projectId: 'storyteller-d0cdd',
    storageBucket: 'storyteller-d0cdd.appspot.com',
    iosClientId: '41295353179-7ctlfppp9a1971850kqerktucqvdkflu.apps.googleusercontent.com',
    iosBundleId: 'com.example.storyteller',
  );
}
